import type {
  BusinessSettings,
  FollowUp,
  FollowupStep,
  Invoice,
  Lead,
  Message,
} from "./types";

// Deterministic "hours ago" timestamps so the demo always looks fresh.
const hoursAgo = (h: number) => new Date(Date.now() - h * 3600_000).toISOString();
const inHours = (h: number) => new Date(Date.now() + h * 3600_000).toISOString();
const daysAgoDate = (d: number) =>
  new Date(Date.now() - d * 86_400_000).toISOString().slice(0, 10);

export const DEMO_LEADS: Lead[] = [
  {
    id: "lead-01",
    name: "Marta Kowalska",
    email: "marta.k@gmail.com",
    phone: "+31 6 1234 5678",
    source: "website",
    message: "Hi, I need my bathroom regrouted before the 20th — can you give me a quote?",
    status: "new",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(0.4),
    last_contacted_at: null,
  },
  {
    id: "lead-02",
    name: "Tom Verhoeven",
    email: null,
    phone: "+31 6 8765 4321",
    source: "whatsapp",
    message: "Saw your work on Instagram. Do you do full kitchen renovations?",
    status: "new",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(2.5),
    last_contacted_at: null,
  },
  {
    id: "lead-03",
    name: "Aisha Benali",
    email: "aisha.benali@outlook.com",
    phone: null,
    source: "website",
    message: "Looking for a monthly cleaning contract for a 3-room office in Rotterdam.",
    status: "new",
    notes: "Recurring contract — priority. Ask about weekend access.",
    appointment_at: null,
    created_at: hoursAgo(7),
    last_contacted_at: null,
  },
  {
    id: "lead-04",
    name: "Jeroen de Wit",
    email: "j.dewit@planet.nl",
    phone: "+31 6 5551 2233",
    source: "website",
    message: "Leaking radiator upstairs, need someone this week if possible.",
    status: "contacted",
    notes: "Booked for Thursday morning. Lindenstraat 42.",
    appointment_at: inHours(40),
    created_at: hoursAgo(26),
    last_contacted_at: hoursAgo(22),
  },
  {
    id: "lead-05",
    name: "Sofia Lindqvist",
    email: "sofia.lq@icloud.com",
    phone: "+31 6 4433 2211",
    source: "whatsapp",
    message: "How much for exterior window cleaning, 2-story house?",
    status: "contacted",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(30),
    last_contacted_at: hoursAgo(5),
  },
  {
    id: "lead-06",
    name: "Daan Bakker",
    email: "daanbakker88@gmail.com",
    phone: null,
    source: "website",
    message: "Quote request: repaint living room + hallway, ~60m². Timeline flexible.",
    status: "contacted",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(50),
    last_contacted_at: hoursAgo(20),
  },
  {
    id: "lead-07",
    name: "Fatima El Amrani",
    email: "f.elamrani@gmail.com",
    phone: "+31 6 9988 7766",
    source: "whatsapp",
    message: "You did my neighbour's garden — can you do ours too? Small backyard.",
    status: "won",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(96),
    last_contacted_at: hoursAgo(80),
  },
  {
    id: "lead-08",
    name: "Rick van Dam",
    email: "rickvd@hotmail.com",
    phone: "+31 6 1122 3344",
    source: "website",
    message: "Need a certified electrician for a fuse box replacement.",
    status: "won",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(120),
    last_contacted_at: hoursAgo(100),
  },
  {
    id: "lead-09",
    name: "Elena Petrova",
    email: "elena.petrova@yahoo.com",
    phone: null,
    source: "website",
    message: "Do you also do small moves? Studio apartment, within the city.",
    status: "lost",
    notes: "Outside our service area.",
    appointment_at: null,
    created_at: hoursAgo(140),
    last_contacted_at: hoursAgo(139),
  },
  {
    id: "lead-10",
    name: "Bram Jansen",
    email: "bram.jansen@live.nl",
    phone: "+31 6 6677 8899",
    source: "whatsapp",
    message: "Price for gutter cleaning, terraced house?",
    status: "won",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(180),
    last_contacted_at: hoursAgo(160),
  },
  {
    id: "lead-11",
    name: "Nadia Haddad",
    email: "nadia.h@gmail.com",
    phone: "+31 6 2211 4455",
    source: "website",
    message: "Hi! Wondering if you have availability for a deep clean before a viewing on Saturday.",
    status: "lost",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(200),
    last_contacted_at: null,
  },
  {
    id: "lead-12",
    name: "Pieter Smit",
    email: "psmit@xs4all.nl",
    phone: "+31 6 3344 5566",
    source: "website",
    message: "Annual boiler service — what do you charge?",
    status: "contacted",
    notes: null,
    appointment_at: null,
    created_at: hoursAgo(12),
    last_contacted_at: hoursAgo(1),
  },
];

// v1 is owner-only: outbound entries are alerts Kept sent to the OWNER,
// never messages to the lead.
export const DEMO_MESSAGES: Message[] = [
  {
    id: "msg-01",
    lead_id: "lead-01",
    direction: "inbound",
    channel: "email",
    body: "Hi, I need my bathroom regrouted before the 20th — can you give me a quote?",
    status: "received",
    created_at: hoursAgo(0.4),
  },
  {
    id: "msg-02",
    lead_id: "lead-01",
    direction: "outbound",
    channel: "reminder",
    body: "New lead: Marta Kowalska (website form) — “I need my bathroom regrouted before the 20th…”. Reply fast to win the job.",
    status: "sent",
    created_at: hoursAgo(0.39),
  },
  {
    id: "msg-03",
    lead_id: "lead-04",
    direction: "inbound",
    channel: "email",
    body: "Leaking radiator upstairs, need someone this week if possible.",
    status: "received",
    created_at: hoursAgo(26),
  },
  {
    id: "msg-04",
    lead_id: "lead-04",
    direction: "outbound",
    channel: "reminder",
    body: "New lead: Jeroen de Wit (website form) — “Leaking radiator upstairs, need someone this week…”.",
    status: "sent",
    created_at: hoursAgo(25.9),
  },
  {
    id: "msg-05",
    lead_id: "lead-04",
    direction: "outbound",
    channel: "reminder",
    body: "Jeroen de Wit enquired yesterday and hasn't heard back from you yet. A quick reply now wins the job.",
    status: "sent",
    created_at: hoursAgo(25),
  },
  {
    id: "msg-06",
    lead_id: "lead-04",
    direction: "inbound",
    channel: "email",
    body: "Yes please — Thursday morning works. Address is Lindenstraat 42.",
    status: "received",
    created_at: hoursAgo(22),
  },
  {
    id: "msg-07",
    lead_id: "lead-02",
    direction: "inbound",
    channel: "whatsapp",
    body: "Saw your work on Instagram. Do you do full kitchen renovations?",
    status: "received",
    created_at: hoursAgo(2.5),
  },
  {
    id: "msg-08",
    lead_id: "lead-02",
    direction: "outbound",
    channel: "reminder",
    body: "New lead: Tom Verhoeven (WhatsApp) — “Do you do full kitchen renovations?”.",
    status: "sent",
    created_at: hoursAgo(2.45),
  },
];

export const DEMO_FOLLOWUPS: FollowUp[] = [
  {
    id: "fu-01",
    lead_id: "lead-01",
    kind: "reminder",
    channel: "reminder",
    template:
      "{{name}} enquired yesterday and hasn't heard back from you yet. A quick reply now wins the job.",
    run_at: inHours(15),
    status: "pending",
  },
  {
    id: "fu-02",
    lead_id: "lead-01",
    kind: "reminder",
    channel: "reminder",
    template: "It's been 2 days since {{name}} reached out. Leads go cold fast — call or message them today.",
    run_at: inHours(39),
    status: "pending",
  },
  {
    id: "fu-03",
    lead_id: "lead-01",
    kind: "reminder",
    channel: "reminder",
    template: "{{name}} has been open for 3 days. Follow up one more time or mark them as lost.",
    run_at: inHours(71.6),
    status: "pending",
  },
  {
    id: "fu-04",
    lead_id: "lead-02",
    kind: "reminder",
    channel: "reminder",
    template: "{{name}} enquired yesterday and hasn't heard back from you yet.",
    run_at: hoursAgo(1.5),
    status: "sent",
  },
  {
    id: "fu-05",
    lead_id: "lead-02",
    kind: "reminder",
    channel: "reminder",
    template: "It's been 2 days since {{name}} reached out. Leads go cold fast.",
    run_at: inHours(45.5),
    status: "pending",
  },
  {
    id: "fu-06",
    lead_id: "lead-04",
    kind: "reminder",
    channel: "reminder",
    template: "It's been 2 days since {{name}} reached out.",
    run_at: inHours(0),
    status: "cancelled",
  },
];

export const DEMO_SETTINGS: BusinessSettings = {
  business_id: "demo-business",
  business_name: "Van Dijk Home Services",
  intake_key: "demo1234abcd5678",
  plan: "trial",
  trial_ends_at: inHours(24 * 2),
  instant_reply_enabled: false,
  instant_reply_channel: "email",
  instant_reply_template:
    "Hi {{name}}, thanks for reaching out! We've received your message and will get back to you shortly.",
  new_lead_alert_enabled: true,
  reminder_enabled: true,
  reminder_delay_minutes: 30,
  notify_email: "owner@vandijkhome.nl",
  from_email: "hello@vandijkhome.nl",
  business_address: "Hoofdstraat 21\n2611 AB Delft",
  whatsapp_from: "+31 6 1000 2000",
  sms_from: "",
  sms_addon_enabled: false,
  invoice_prefix: "INV",
  invoice_currency: "EUR",
  invoice_tax_rate: 21,
  invoice_footer: "Payment within 14 days to NL00 BANK 0123 4567 89.",
  reply_templates: [
    "Hi {{name}}, thanks for reaching out! I'd be happy to help — when is a good moment to call you today?",
    "Hi {{name}}, I can come by for a free quote this week. Which day suits you?",
  ],
  weekly_digest_enabled: true,
  price_book: [
    { description: "Call-out & diagnosis", unit_price: 45 },
    { description: "Bathroom regrouting (per m2)", unit_price: 38 },
    { description: "Gutter cleaning, terraced house", unit_price: 120 },
  ],
  page_enabled: true,
  page_tagline: "Plumbing, tiling & home repairs in Delft — fast quotes, tidy work.",
  page_services:
    "Bathroom renovation\nLeak repair & boiler service\nTiling & grouting\nGutter cleaning",
};

// v1 defaults: every step nudges the OWNER (channel "reminder").
export const DEMO_STEPS: FollowupStep[] = [
  {
    id: "step-1",
    step_order: 1,
    delay_minutes: 1440,
    channel: "reminder",
    template:
      "{{name}} enquired yesterday and hasn't heard back from you yet. A quick reply now wins the job.",
    enabled: true,
  },
  {
    id: "step-2",
    step_order: 2,
    delay_minutes: 2880,
    channel: "reminder",
    template:
      "It's been 2 days since {{name}} reached out. Leads go cold fast — call or message them today.",
    enabled: true,
  },
  {
    id: "step-3",
    step_order: 3,
    delay_minutes: 4320,
    channel: "reminder",
    template: "{{name}} has been open for 3 days. Follow up one more time or mark them as lost.",
    enabled: true,
  },
];

export const DEMO_INVOICES: Invoice[] = [
  {
    id: "inv-01",
    number: "INV-0003",
    status: "sent",
    doc_type: "invoice",
    recurs: null,
    next_recurrence: null,
    client_name: "Fatima El Amrani",
    client_email: "f.elamrani@gmail.com",
    client_address: "Rozenlaan 12\n3014 AB Rotterdam",
    issue_date: daysAgoDate(2),
    due_date: daysAgoDate(-12),
    currency: "EUR",
    tax_rate: 21,
    discount: 0,
    items: [
      { description: "Garden clearing & landscaping (small backyard)", qty: 1, unit_price: 480 },
      { description: "Green waste disposal", qty: 1, unit_price: 45 },
    ],
    notes: "Thanks for your business!",
    paid_at: null,
    created_at: hoursAgo(48),
  },
  {
    id: "inv-02",
    number: "INV-0002",
    status: "paid",
    doc_type: "invoice",
    recurs: null,
    next_recurrence: null,
    client_name: "Rick van Dam",
    client_email: "rickvd@hotmail.com",
    client_address: "Kerkstraat 8\n1017 GL Amsterdam",
    issue_date: daysAgoDate(6),
    due_date: daysAgoDate(-8),
    currency: "EUR",
    tax_rate: 21,
    discount: 25,
    items: [
      { description: "Fuse box replacement (incl. materials)", qty: 1, unit_price: 640 },
      { description: "Certification & inspection report", qty: 1, unit_price: 95 },
    ],
    notes: null,
    paid_at: hoursAgo(20),
    created_at: hoursAgo(144),
  },
  {
    id: "inv-03",
    number: "INV-0001",
    status: "paid",
    doc_type: "invoice",
    recurs: null,
    next_recurrence: null,
    client_name: "Bram Jansen",
    client_email: "bram.jansen@live.nl",
    client_address: null,
    issue_date: daysAgoDate(9),
    due_date: daysAgoDate(-5),
    currency: "EUR",
    tax_rate: 21,
    discount: 0,
    items: [{ description: "Gutter cleaning, terraced house", qty: 1, unit_price: 120 }],
    notes: null,
    paid_at: hoursAgo(96),
    created_at: hoursAgo(216),
  },
];

/** Leads received per day for the last 14 days (demo trend, oldest first). */
export const DEMO_LEADS_PER_DAY: { date: string; count: number }[] = Array.from(
  { length: 14 },
  (_, i) => {
    const d = new Date(Date.now() - (13 - i) * 86_400_000);
    // A believable small-business rhythm: quiet Sundays, busy mid-week.
    const pattern = [3, 5, 6, 4, 7, 4, 1, 4, 6, 8, 5, 7, 6, 2];
    return {
      date: d.toISOString().slice(0, 10),
      count: pattern[i],
    };
  }
);
